# Generated by Django 2.2.6 on 2019-10-28 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=100)),
                ('app_name', models.CharField(default='---', max_length=100)),
                ('page_name', models.CharField(default='---', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('go_up', models.CharField(default='../', max_length=100)),
                ('msg', models.CharField(default='---', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '頁面主檔',
                'verbose_name_plural': '頁面主檔',
                'unique_together': {('app', 'page')},
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='---', max_length=100)),
                ('app', models.CharField(max_length=100)),
                ('seq', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=300)),
                ('btn', models.CharField(default='btn-info', max_length=300)),
                ('disp', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('encoder', models.CharField(blank=True, max_length=30, null=True, verbose_name='數據維護人員')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Index主檔',
                'verbose_name_plural': 'Index主檔',
            },
        ),
        migrations.CreateModel(
            name='LogAppPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=100)),
                ('data', models.CharField(default='---', max_length=300)),
                ('ip', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=300)),
                ('stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.CharField(max_length=100)),
                ('seq', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('note1', models.CharField(max_length=300)),
                ('note2', models.CharField(max_length=300)),
                ('note', models.TextField(default='---')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Note',
            },
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('note', models.CharField(default='---', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SOP',
                'verbose_name_plural': 'SOP',
            },
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='主題')),
                ('brief', models.CharField(max_length=300, verbose_name='簡述')),
                ('status', models.CharField(max_length=30, verbose_name='狀態')),
                ('doer', models.CharField(blank=True, max_length=100, null=True, verbose_name='數據維護')),
                ('detail', models.TextField(blank=True, max_length=1000, null=True, verbose_name='詳情')),
                ('priority', models.IntegerField(default=0, verbose_name='權重')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODO',
            },
        ),
        migrations.CreateModel(
            name='SOPDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('frequency', models.CharField(default='每日', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='備註')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.SOP')),
            ],
            options={
                'verbose_name': 'SOP detail',
                'verbose_name_plural': 'SOP detail',
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='AppPageGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.CharField(max_length=100)),
                ('apppage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AppPage', verbose_name='AppPage')),
            ],
        ),
        migrations.CreateModel(
            name='AppPageAuthGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=100)),
                ('authgrp', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'APP-PAGE-AuthGrp',
                'verbose_name_plural': 'APP-PAGE-AuthGrp',
                'unique_together': {('app', 'page')},
            },
        ),
        migrations.CreateModel(
            name='AppPageMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=300)),
                ('btn', models.CharField(default='btn-info', max_length=300)),
                ('disp', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apppage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AppPage', verbose_name='AppPage')),
            ],
            options={
                'verbose_name': '頁面主檔菜單',
                'verbose_name_plural': '頁面主檔菜單',
                'ordering': ['seq'],
                'unique_together': {('apppage', 'disp')},
            },
        ),
    ]
