# Generated by Django 2.2.6 on 2019-11-09 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('member', models.CharField(choices=[('Member', 'Member'), ('Guest', 'Guest')], max_length=6, verbose_name='Member')),
                ('date1', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('role', models.CharField(choices=[('Attendance', 'Attendance'), ('Ah-counter', 'Ah-counter'), ('GE', 'GE'), ('Grammarian', 'Grammarian'), ('IE', 'IE'), ('Speaker', 'Speaker'), ('TME', 'TME'), ('TT Speaker', 'TT Speaker'), ('TT Evaluator', 'TT Evaluator'), ('TT-master', 'TT-master'), ('Timer', 'Timer')], max_length=32, verbose_name='Role')),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meeting',
                'unique_together': {('name', 'date1', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('title', models.CharField(choices=[('tt', 'tt')], default='tt', max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Meeting Best',
                'verbose_name_plural': 'Meeting Best',
                'unique_together': {('date1', 'title')},
            },
        ),
    ]
