# Generated by Django 2.2.6 on 2019-11-09 04:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=32, verbose_name='Member Nickname')),
                ('fullname', models.CharField(max_length=32, verbose_name='Member Fullname')),
                ('is_member', models.BooleanField(default=True, verbose_name='Is Member')),
                ('member_since', models.DateField(default=datetime.date.today, verbose_name='Member Since')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='Club')),
            ],
            options={
                'unique_together': {('club', 'member')},
            },
        ),
        migrations.CreateModel(
            name='ClubDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='Club')),
            ],
            options={
                'unique_together': {('club', 'date1')},
            },
        ),
        migrations.CreateModel(
            name='Attd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.ClubDate', verbose_name='Club')),
                ('clubmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.ClubMember', verbose_name='Club')),
            ],
            options={
                'unique_together': {('clubdate', 'clubmember')},
            },
        ),
    ]
