# Generated by Django 2.2.6 on 2019-11-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_attd_clubdate_clubmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmember',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='clubmember',
            name='member_since',
        ),
    ]
