# Generated by Django 2.2.6 on 2019-11-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20191109_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Toastmaster Roles',
                'verbose_name_plural': 'Toastmaster Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='attd',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='attd',
            name='clubdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.ClubDate', verbose_name='Club Date'),
        ),
        migrations.AlterField(
            model_name='attd',
            name='clubmember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.ClubMember', verbose_name='Club Member'),
        ),
    ]
