# Generated by Django 2.2.6 on 2019-11-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20191109_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attd',
            options={'verbose_name': 'Attd', 'verbose_name_plural': 'Attd'},
        ),
        migrations.AlterModelOptions(
            name='attdrole',
            options={'verbose_name': 'Attd Role', 'verbose_name_plural': 'Attd Role'},
        ),
    ]
